# Generated by Django 5.0.3 on 2024-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('purdue_email', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('H', 'Hitter'), ('S', 'Setter'), ('L', 'Libero'), ('F', 'Flex')], max_length=1)),
            ],
        ),
    ]
