# Generated by Django 5.0.3 on 2024-03-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='puid',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
