# Generated by Django 5.0.3 on 2024-03-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_puid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='puid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
